services:
  app:
    container_name: rawej
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
    extra_hosts:
      - "api.psychometrist.local:host-gateway"
